// Auto-generated by: supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/supabase/types.ts
// Regenerate after any schema change.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      vehicles: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          brand_id: string | null;
          vehicle_type_id: string | null;
          reference_id: string | null;
          plate: string | null;
          model_year: number | null;
          current_km: number;
          soat_expiry: string | null;
          inspection_expiry: string | null;
          oil_reference: string | null;
          image_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          brand_id?: string | null;
          vehicle_type_id?: string | null;
          reference_id?: string | null;
          plate?: string | null;
          model_year?: number | null;
          current_km?: number;
          soat_expiry?: string | null;
          inspection_expiry?: string | null;
          oil_reference?: string | null;
          image_url?: string | null;
          is_active?: boolean;
        };
        Update: {
          name?: string;
          description?: string | null;
          brand_id?: string | null;
          vehicle_type_id?: string | null;
          reference_id?: string | null;
          plate?: string | null;
          model_year?: number | null;
          current_km?: number;
          soat_expiry?: string | null;
          inspection_expiry?: string | null;
          oil_reference?: string | null;
          image_url?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      vehicle_licenses: {
        Row: {
          id: string;
          user_id: string;
          vehicle_id: string | null;
          stripe_subscription_id: string | null;
          stripe_item_id: string | null;
          status: "active" | "canceled" | "past_due" | "trialing";
          valid_until: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          vehicle_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_item_id?: string | null;
          status?: "active" | "canceled" | "past_due" | "trialing";
          valid_until?: string | null;
        };
        Update: {
          vehicle_id?: string | null;
          status?: "active" | "canceled" | "past_due" | "trialing";
          valid_until?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      km_updates: {
        Row: {
          id: string;
          user_id: string;
          vehicle_id: string;
          km_value: number;
          notes: string | null;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          vehicle_id: string;
          km_value: number;
          notes?: string | null;
          recorded_at?: string;
        };
        Update: {
          km_value?: number;
          notes?: string | null;
        };
        Relationships: [];
      };
      maintenances: {
        Row: {
          id: string;
          user_id: string;
          vehicle_id: string;
          date: string;
          km_at_service: number | null;
          workshop: string | null;
          notes: string | null;
          total_cost: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          vehicle_id: string;
          date?: string;
          km_at_service?: number | null;
          workshop?: string | null;
          notes?: string | null;
          total_cost?: number;
        };
        Update: {
          date?: string;
          km_at_service?: number | null;
          workshop?: string | null;
          notes?: string | null;
          total_cost?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      maintenance_details: {
        Row: {
          id: string;
          maintenance_id: string;
          action_id: string | null;
          supply_id: string | null;
          detail: string | null;
          cost: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          maintenance_id: string;
          action_id?: string | null;
          supply_id?: string | null;
          detail?: string | null;
          cost?: number;
        };
        Update: {
          action_id?: string | null;
          supply_id?: string | null;
          detail?: string | null;
          cost?: number;
        };
        Relationships: [];
      };
      vehicle_types: {
        Row: { id: string; name: string; icon: string | null; created_at: string };
        Insert: { id?: string; name: string; icon?: string | null };
        Update: { name?: string; icon?: string | null };
        Relationships: [];
      };
      brands: {
        Row: {
          id: string;
          name: string;
          vehicle_type_id: string | null;
          created_at: string;
        };
        Insert: { id?: string; name: string; vehicle_type_id?: string | null };
        Update: { name?: string; vehicle_type_id?: string | null };
        Relationships: [];
      };
      vehicle_references: {
        Row: {
          id: string;
          name: string;
          brand_id: string | null;
          created_at: string;
        };
        Insert: { id?: string; name: string; brand_id?: string | null };
        Update: { name?: string; brand_id?: string | null };
        Relationships: [];
      };
      maintenance_actions: {
        Row: { id: string; name: string; category: string | null; created_at: string };
        Insert: { id?: string; name: string; category?: string | null };
        Update: { name?: string; category?: string | null };
        Relationships: [];
      };
      supplies: {
        Row: { id: string; name: string; unit: string | null; created_at: string };
        Insert: { id?: string; name: string; unit?: string | null };
        Update: { name?: string; unit?: string | null };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
        };
        Update: {
          endpoint?: string;
          p256dh?: string;
          auth?: string;
        };
        Relationships: [];
      };
      ads: {
        Row: {
          id: string;
          image_url: string | null;
          link_url: string | null;
          sponsor_name: string;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          image_url?: string | null;
          link_url?: string | null;
          sponsor_name: string;
          active?: boolean;
        };
        Update: {
          image_url?: string | null;
          link_url?: string | null;
          sponsor_name?: string;
          active?: boolean;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
